class SamsungElectronicsProfile extends CompanyProfile { SamsungElectronicsProfile() { super("삼성전자", "반도체"); } }
class SkHynixProfile extends CompanyProfile { SkHynixProfile() { super("SK하이닉스", "반도체"); } }
class LgEnergySolutionProfile extends CompanyProfile { LgEnergySolutionProfile() { super("LG에너지솔루션", "2차전지"); } }
class SamsungBiologicsProfile extends CompanyProfile { SamsungBiologicsProfile() { super("삼성바이오로직스", "바이오"); } }
class HyundaiMotorProfile extends CompanyProfile { HyundaiMotorProfile() { super("현대차", "자동차"); } }
class KiaProfile extends CompanyProfile { KiaProfile() { super("기아", "자동차"); } }
class CelltrionProfile extends CompanyProfile { CelltrionProfile() { super("셀트리온", "바이오"); } }
class PoscoHoldingsProfile extends CompanyProfile { PoscoHoldingsProfile() { super("POSCO홀딩스", "철강"); } }
class NaverProfile extends CompanyProfile { NaverProfile() { super("NAVER", "인터넷"); } }
class KakaoProfile extends CompanyProfile { KakaoProfile() { super("카카오", "인터넷"); } }
class HyundaiMobisProfile extends CompanyProfile { HyundaiMobisProfile() { super("현대모비스", "자동차부품"); } }
class SamsungSdiProfile extends CompanyProfile { SamsungSdiProfile() { super("삼성SDI", "2차전지"); } }
class LgChemProfile extends CompanyProfile { LgChemProfile() { super("LG화학", "화학"); } }
class KbFinancialProfile extends CompanyProfile { KbFinancialProfile() { super("KB금융", "금융"); } }
class ShinhanFinancialProfile extends CompanyProfile { ShinhanFinancialProfile() { super("신한지주", "금융"); } }
class HanaFinancialProfile extends CompanyProfile { HanaFinancialProfile() { super("하나금융지주", "금융"); } }
class SamsungCAndTProfile extends CompanyProfile { SamsungCAndTProfile() { super("삼성물산", "지주"); } }
class LgElectronicsProfile extends CompanyProfile { LgElectronicsProfile() { super("LG전자", "전자"); } }
class SkInnovationProfile extends CompanyProfile { SkInnovationProfile() { super("SK이노베이션", "에너지"); } }
class PoscoFutureMProfile extends CompanyProfile { PoscoFutureMProfile() { super("포스코퓨처엠", "2차전지소재"); } }
class HanwhaAerospaceProfile extends CompanyProfile { HanwhaAerospaceProfile() { super("한화에어로스페이스", "방산"); } }
class HyundaiHeavyProfile extends CompanyProfile { HyundaiHeavyProfile() { super("현대중공업", "조선"); } }
class HdKsoeProfile extends CompanyProfile { HdKsoeProfile() { super("HD한국조선해양", "조선"); } }
class SamsungElectroMechanicsProfile extends CompanyProfile { SamsungElectroMechanicsProfile() { super("삼성전기", "전자부품"); } }
class KakaoBankProfile extends CompanyProfile { KakaoBankProfile() { super("카카오뱅크", "금융"); } }
class KraftonProfile extends CompanyProfile { KraftonProfile() { super("크래프톤", "게임"); } }
class HybeProfile extends CompanyProfile { HybeProfile() { super("하이브", "엔터테인먼트"); } }
class NcsoftProfile extends CompanyProfile { NcsoftProfile() { super("엔씨소프트", "게임"); } }
class AmorePacificProfile extends CompanyProfile { AmorePacificProfile() { super("아모레퍼시픽", "화장품"); } }
class KoreanAirProfile extends CompanyProfile { KoreanAirProfile() { super("대한항공", "항공"); } }
class LgHouseholdProfile extends CompanyProfile { LgHouseholdProfile() { super("LG생활건강", "생활소비재"); } }
class LotteChemicalProfile extends CompanyProfile { LotteChemicalProfile() { super("롯데케미칼", "화학"); } }
class SOilProfile extends CompanyProfile { SOilProfile() { super("S-Oil", "정유"); } }
class KepcoProfile extends CompanyProfile { KepcoProfile() { super("한국전력", "전력"); } }
class KtngProfile extends CompanyProfile { KtngProfile() { super("KT&G", "소비재"); } }
class SamsungFireProfile extends CompanyProfile { SamsungFireProfile() { super("삼성화재", "보험"); } }
class MiraeAssetProfile extends CompanyProfile { MiraeAssetProfile() { super("미래에셋증권", "증권"); } }
class DoosanEnerbilityProfile extends CompanyProfile { DoosanEnerbilityProfile() { super("두산에너빌리티", "에너지설비"); } }
class EcoproProfile extends CompanyProfile { EcoproProfile() { super("에코프로", "2차전지소재"); } }
class EcoproBmProfile extends CompanyProfile { EcoproBmProfile() { super("에코프로비엠", "2차전지소재"); } }
