class SamsungElectronicsNewsKeyword implements NewsKeywordProfile { public String keyword() { return "삼성전자 주가 실적 전망"; } }
class SkHynixNewsKeyword implements NewsKeywordProfile { public String keyword() { return "SK하이닉스 주가 실적 전망"; } }
class LgEnergySolutionNewsKeyword implements NewsKeywordProfile { public String keyword() { return "LG에너지솔루션 주가 실적 전망"; } }
class SamsungBiologicsNewsKeyword implements NewsKeywordProfile { public String keyword() { return "삼성바이오로직스 주가 실적 전망"; } }
class HyundaiMotorNewsKeyword implements NewsKeywordProfile { public String keyword() { return "현대차 주가 실적 전망"; } }
class KiaNewsKeyword implements NewsKeywordProfile { public String keyword() { return "기아 주가 실적 전망"; } }
class CelltrionNewsKeyword implements NewsKeywordProfile { public String keyword() { return "셀트리온 주가 실적 전망"; } }
class PoscoHoldingsNewsKeyword implements NewsKeywordProfile { public String keyword() { return "POSCO홀딩스 주가 실적 전망"; } }
class NaverNewsKeyword implements NewsKeywordProfile { public String keyword() { return "NAVER 주가 실적 전망"; } }
class KakaoNewsKeyword implements NewsKeywordProfile { public String keyword() { return "카카오 주가 실적 전망"; } }
class HyundaiMobisNewsKeyword implements NewsKeywordProfile { public String keyword() { return "현대모비스 주가 실적 전망"; } }
class SamsungSdiNewsKeyword implements NewsKeywordProfile { public String keyword() { return "삼성SDI 주가 실적 전망"; } }
class LgChemNewsKeyword implements NewsKeywordProfile { public String keyword() { return "LG화학 주가 실적 전망"; } }
class KbFinancialNewsKeyword implements NewsKeywordProfile { public String keyword() { return "KB금융 주가 실적 전망"; } }
class ShinhanFinancialNewsKeyword implements NewsKeywordProfile { public String keyword() { return "신한지주 주가 실적 전망"; } }
class HanaFinancialNewsKeyword implements NewsKeywordProfile { public String keyword() { return "하나금융지주 주가 실적 전망"; } }
class SamsungCAndTNewsKeyword implements NewsKeywordProfile { public String keyword() { return "삼성물산 주가 실적 전망"; } }
class LgElectronicsNewsKeyword implements NewsKeywordProfile { public String keyword() { return "LG전자 주가 실적 전망"; } }
class SkInnovationNewsKeyword implements NewsKeywordProfile { public String keyword() { return "SK이노베이션 주가 실적 전망"; } }
class PoscoFutureMNewsKeyword implements NewsKeywordProfile { public String keyword() { return "포스코퓨처엠 주가 실적 전망"; } }
class HanwhaAerospaceNewsKeyword implements NewsKeywordProfile { public String keyword() { return "한화에어로스페이스 주가 실적 전망"; } }
class HyundaiHeavyNewsKeyword implements NewsKeywordProfile { public String keyword() { return "현대중공업 주가 실적 전망"; } }
class HdKsoeNewsKeyword implements NewsKeywordProfile { public String keyword() { return "HD한국조선해양 주가 실적 전망"; } }
class SamsungElectroMechanicsNewsKeyword implements NewsKeywordProfile { public String keyword() { return "삼성전기 주가 실적 전망"; } }
class KakaoBankNewsKeyword implements NewsKeywordProfile { public String keyword() { return "카카오뱅크 주가 실적 전망"; } }
class KraftonNewsKeyword implements NewsKeywordProfile { public String keyword() { return "크래프톤 주가 실적 전망"; } }
class HybeNewsKeyword implements NewsKeywordProfile { public String keyword() { return "하이브 주가 실적 전망"; } }
class NcsoftNewsKeyword implements NewsKeywordProfile { public String keyword() { return "엔씨소프트 주가 실적 전망"; } }
class AmorePacificNewsKeyword implements NewsKeywordProfile { public String keyword() { return "아모레퍼시픽 주가 실적 전망"; } }
class KoreanAirNewsKeyword implements NewsKeywordProfile { public String keyword() { return "대한항공 주가 실적 전망"; } }
class LgHouseholdNewsKeyword implements NewsKeywordProfile { public String keyword() { return "LG생활건강 주가 실적 전망"; } }
class LotteChemicalNewsKeyword implements NewsKeywordProfile { public String keyword() { return "롯데케미칼 주가 실적 전망"; } }
class SOilNewsKeyword implements NewsKeywordProfile { public String keyword() { return "S-Oil 주가 실적 전망"; } }
class KepcoNewsKeyword implements NewsKeywordProfile { public String keyword() { return "한국전력 주가 실적 전망"; } }
class KtngNewsKeyword implements NewsKeywordProfile { public String keyword() { return "KT&G 주가 실적 전망"; } }
class SamsungFireNewsKeyword implements NewsKeywordProfile { public String keyword() { return "삼성화재 주가 실적 전망"; } }
class MiraeAssetNewsKeyword implements NewsKeywordProfile { public String keyword() { return "미래에셋증권 주가 실적 전망"; } }
class DoosanEnerbilityNewsKeyword implements NewsKeywordProfile { public String keyword() { return "두산에너빌리티 주가 실적 전망"; } }
class EcoproNewsKeyword implements NewsKeywordProfile { public String keyword() { return "에코프로 주가 실적 전망"; } }
class EcoproBmNewsKeyword implements NewsKeywordProfile { public String keyword() { return "에코프로비엠 주가 실적 전망"; } }
